// Autogenerated from Pigeon (v17.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class F2NMessage;
@class N2FMessage;

@interface F2NMessage : NSObject
+ (instancetype)makeWithMsg:(nullable NSString *)msg;
@property(nonatomic, copy, nullable) NSString * msg;
@end

@interface N2FMessage : NSObject
+ (instancetype)makeWithMsg2:(nullable NSString *)msg2;
@property(nonatomic, copy, nullable) NSString * msg2;
@end

/// The codec used by FlutterMessage.
NSObject<FlutterMessageCodec> *FlutterMessageGetCodec(void);

/// flutter发往native的方法flutterSendMessage
@protocol FlutterMessage
- (void)flutterSendMessageMsg:(F2NMessage *)msg error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpFlutterMessage(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FlutterMessage> *_Nullable api);

/// The codec used by NativeMessage.
NSObject<FlutterMessageCodec> *NativeMessageGetCodec(void);

/// native发往flutter的方法nativeSendMessage
@interface NativeMessage : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)nativeSendMessageMsg:(N2FMessage *)msg completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
