// Autogenerated from Pigeon (v17.1.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class F2NMessage {
  F2NMessage({
    this.msg,
  });

  String? msg;

  Object encode() {
    return <Object?>[
      msg,
    ];
  }

  static F2NMessage decode(Object result) {
    result as List<Object?>;
    return F2NMessage(
      msg: result[0] as String?,
    );
  }
}

class N2FMessage {
  N2FMessage({
    this.msg2,
  });

  String? msg2;

  Object encode() {
    return <Object?>[
      msg2,
    ];
  }

  static N2FMessage decode(Object result) {
    result as List<Object?>;
    return N2FMessage(
      msg2: result[0] as String?,
    );
  }
}

class _FlutterMessageCodec extends StandardMessageCodec {
  const _FlutterMessageCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is F2NMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return F2NMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// flutter发往native的方法flutterSendMessage
class FlutterMessage {
  /// Constructor for [FlutterMessage].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterMessage({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _FlutterMessageCodec();

  Future<void> flutterSendMessage(F2NMessage msg) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.flutter_pigeon_plugin.FlutterMessage.flutterSendMessage';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[msg]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

class _NativeMessageCodec extends StandardMessageCodec {
  const _NativeMessageCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is N2FMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return N2FMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// native发往flutter的方法nativeSendMessage
abstract class NativeMessage {
  static const MessageCodec<Object?> pigeonChannelCodec = _NativeMessageCodec();

  void nativeSendMessage(N2FMessage msg);

  static void setup(NativeMessage? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_pigeon_plugin.NativeMessage.nativeSendMessage', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_pigeon_plugin.NativeMessage.nativeSendMessage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final N2FMessage? arg_msg = (args[0] as N2FMessage?);
          assert(arg_msg != null,
              'Argument for dev.flutter.pigeon.flutter_pigeon_plugin.NativeMessage.nativeSendMessage was null, expected non-null N2FMessage.');
          try {
            api.nativeSendMessage(arg_msg!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
